version: '3.1'

services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: "+IcoKg1B530IWS+MnPXcnsFqGXvXu1T6/96GoqgL7oo="
    ports:
      - "5436:5432"
    volumes:
      - my_dbdata:/var/lib/postgresql/data

volumes:
  my_dbdata:
